import type { NextPage } from "next";
import Head from "next/head";
import { Card, CardField, CardList } from "../components";
import styles from "../styles/Home.module.css";

import { FaMoneyBillWave, FaSeedling, FaSave } from "react-icons/fa";
import { BsGraphUp } from "react-icons/bs";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.menu}>
          <div className={styles.wrapperButton}>
            <button>
              <FaSeedling style={{ fontSize: 35 }} />
              <span>Criar</span>
            </button>
            <button>
              <BsGraphUp style={{ fontSize: 35 }} />
              <span>Otimizar</span>
            </button>
            <button>
              <FaSave style={{ fontSize: 35 }} />
              <span>Salvar</span>
            </button>
          </div>
        </div>
        <div className={styles.body}>
          <div className={styles.optionSection}>
            <h1>Agriculture-Optimizer</h1>
            <div className={styles.wrapperRow}>
              <Card title="Investimento" icon={FaMoneyBillWave} />
              <Card title="Investimento" icon={FaMoneyBillWave} />
              <Card title="Investimento" />
            </div>
          </div>
          <div className={styles.areaSection}>
            <h2>Manage your fields</h2>
            <div className={styles.wrapperRow}>
              <CardField title="Investimento" />
              <CardField title="Investimento" />
            </div>
          </div>
          <div className={styles.plantSection}>
            <h2>Manage your plants</h2>
            <div className={styles.wrapperColumn}>
              <CardList title="Investimento" />
              <CardList title="Investimento" />
            </div>
          </div>
          <button className={styles.button}>Otimizar</button>
        </div>
      </main>
    </>
  );
};

export default Home;
