import type { NextPage } from "next";
import Head from "next/head";
import {
  Card,
  CardField,
  CardList,
  ModalField,
  ModalInvestimento,
  ModalPlant,
} from "../components";
import styles from "../styles/Home.module.css";

import { FaSeedling, FaSave } from "react-icons/fa";
import { BsFileEarmarkBarGraph, BsCurrencyDollar } from "react-icons/bs";
import { useState } from "react";

type fieldProps = {
  name: string;
  area: string;
};

type dataProps = {
  investimento: number | null;
  fields: fieldProps[];
};

const Home: NextPage = () => {
  const [isOpenModalInvestimento, setIsOpenModalInvestimento] = useState(false);
  const [isOpenModalField, setIsOpenModalField] = useState(false);
  const [isOpenModalPlants, setIsOpenModalPlants] = useState(false);

  const [name, setName] = useState("");
  const [area, setArea] = useState("");
  const [investimento, setInvestimento] = useState(null);

  const [data, setData] = useState<dataProps>({
    fields: [],
    investimento,
  } as dataProps);

  function addData(newData: fieldProps) {
    setData((prevData) => ({
      investimento: prevData.investimento,
      fields: [...prevData.fields, newData],
    }));
  }

  function addDataInvestimento(newInvestimento: number) {
    setData((prevData) => ({
      investimento: newInvestimento,
      fields: [...prevData.fields],
    }));
  }

  function addDataPlants(newData: fieldProps) {
    setData((prevData) => ({
      investimento: prevData.investimento,
      fields: [...prevData.fields, newData],
    }));
  }

  console.log(data);

  function onChangeModalInvestimento() {
    setIsOpenModalInvestimento(!isOpenModalInvestimento);
  }

  function onChangeModalField() {
    setIsOpenModalField(!isOpenModalField);
  }

  function onChangeModalPlants() {
    setIsOpenModalPlants(!isOpenModalPlants);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isOpenModalInvestimento && (
        <ModalInvestimento
          setIsOpen={setIsOpenModalInvestimento}
          syncData={addDataInvestimento}
        />
      )}
      {isOpenModalField && (
        <ModalField
          setIsOpen={setIsOpenModalField}
          setArea={setArea}
          setName={setName}
          syncData={addData}
        />
      )}
      {isOpenModalPlants && <ModalPlant setIsOpen={setIsOpenModalPlants} />}

      <main className={styles.main}>
        <div className={styles.menu}>
          <div className={styles.wrapperButton}>
            <button>
              <FaSeedling style={{ fontSize: 25 }} />
              <span>Criar</span>
            </button>
            <button>
              <BsFileEarmarkBarGraph style={{ fontSize: 25 }} />
              <span>Otimizar</span>
            </button>
            <button>
              <FaSave style={{ fontSize: 25 }} />
              <span>Salvar</span>
            </button>
          </div>
        </div>
        <div className={styles.body}>
          <div className={styles.optionSection}>
            <h1>Agriculture-Optimizer</h1>
            <div className={styles.wrapperRow}>
              <Card
                investimento={investimento!}
                onChangeModal={onChangeModalInvestimento}
                icon={BsCurrencyDollar}
              />
            </div>
          </div>
          <div className={styles.areaSection}>
            <h2>Manage your fields</h2>
            <div className={styles.wrapperRow}>
              <CardField
                valueArea={area}
                valueName={name}
                onChangeModal={onChangeModalField}
              />
              <CardField
                valueArea={area}
                valueName={name}
                onChangeModal={onChangeModalField}
              />
            </div>
          </div>
          <div className={styles.plantSection}>
            <h2>Manage your plants</h2>
            <div className={styles.wrapperColumn}>
              <CardList />
              <CardList />
            </div>
          </div>
          <button className={styles.button} onClick={() => {}}>
            Otimizar
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
