import type { NextPage } from "next";
import Head from "next/head";
import { Card } from "../components";
import styles from "../styles/Home.module.css";

import { FcMoneyTransfer } from "react-icons/fc";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Card title="Investmento" icon={FcMoneyTransfer} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
